# -------------------------------------------------------------------------------------------------
#  Type stubs for MT5 adapter PyO3 bindings
# -------------------------------------------------------------------------------------------------

class Mt5Config:
    """MT5 configuration class."""

    base_url: str
    http_timeout: int
    proxy: str | None

    def __init__(
        self,
        base_url: str | None = None,
        http_timeout: int | None = None,
        proxy: str | None = None,
    ) -> None: ...

class Mt5HttpClient:
    """MT5 HTTP client for REST API communication."""
    def __init__(self, config: Mt5Config, base_url: str) -> None: ...

    # Basic Information
    async def version(self) -> str: ...
    async def terminal_info(self) -> str: ...
    async def account_info(self) -> str: ...

    # Symbols
    async def symbols_total(self) -> str: ...
    async def symbols_get(self, body: str) -> str: ...
    async def symbol_info(self, body: str) -> str: ...
    async def symbol_info_tick(self, body: str) -> str: ...
    async def symbol_select(self, body: str) -> str: ...

    # Market Data
    async def copy_ticks_from(self, body: str) -> str: ...
    async def copy_ticks_range(self, body: str) -> str: ...
    async def copy_rates_from(self, body: str) -> str: ...
    async def copy_rates_range(self, body: str) -> str: ...

    # Orders
    async def orders_total(self) -> str: ...
    async def orders_get(self) -> str: ...
    async def order_send(self, body: str) -> str: ...
    async def order_check(self, body: str) -> str: ...
    async def order_calc_margin(self, body: str) -> str: ...
    async def order_calc_profit(self, body: str) -> str: ...

    # Positions
    async def positions_total(self) -> str: ...
    async def positions_get(self) -> str: ...

    # History
    async def history_orders_total(self, body: str) -> str: ...
    async def history_orders_get(self, body: str) -> str: ...
    async def history_deals_total(self, body: str) -> str: ...
    async def history_deals_get(self, body: str) -> str: ...

    # Market book
    async def market_book_add(self, body: str) -> str: ...
    async def market_book_release(self, body: str) -> str: ...
    async def market_book_get(self, body: str) -> str: ...

    # System
    async def last_error(self) -> str: ...

    # Session Management
    async def initialize(self) -> str: ...
    async def login(self) -> str: ...
    async def shutdown(self) -> str: ...

class Mt5Credential:
    """MT5 credentials for authentication."""

    login: str
    password: str
    server: str
    proxy: str | None

    def __init__(self, login: str, password: str, server: str) -> None: ...

class Mt5Symbol:
    """MT5 symbol information."""

    name: str
    digits: int
    point: float
    volume_min: float
    volume_max: float
    volume_step: float

__all__: list[str]
