"""Type stubs for nautilus_mt5 Rust bindings."""

from typing import Optional

__version__: str
__all__: list[str]

class Mt5Config:
    """MT5 HTTP client configuration."""
    def __init__(self) -> None: ...

class Mt5Credential:
    """MT5 credentials for authentication."""
    def __init__(self, login: int, password: str, server: str) -> None: ...

class Mt5HttpClient:
    """HTTP client for MT5 REST API."""
    def __init__(self, config: Mt5Config, base_url: str) -> None: ...

    # Connection methods
    async def initialize(self, params: str) -> str: ...
    async def login(self, params: str) -> str: ...
    async def shutdown(self) -> str: ...
    async def version(self) -> str: ...
    async def last_error(self) -> str: ...

    # Account methods
    async def account_info(self) -> str: ...
    async def terminal_info(self) -> str: ...

    # Symbol methods
    async def symbols_total(self) -> str: ...
    async def symbols_get(self, params: str) -> str: ...
    async def symbol_info(self, params: str) -> str: ...
    async def symbol_info_tick(self, params: str) -> str: ...
    async def symbol_select(self, params: str) -> str: ...

    # Market data methods
    async def copy_rates_from(self, params: str) -> str: ...
    async def copy_rates_range(self, params: str) -> str: ...
    async def copy_ticks_from(self, params: str) -> str: ...
    async def copy_ticks_range(self, params: str) -> str: ...

    # Order methods
    async def orders_total(self) -> str: ...
    async def orders_get(self) -> str: ...
    async def positions_total(self) -> str: ...
    async def positions_get(self) -> str: ...
    async def order_send(self, params: str) -> str: ...
    async def order_check(self, params: str) -> str: ...
    async def order_calc_margin(self, params: str) -> str: ...
    async def order_calc_profit(self, params: str) -> str: ...

    # History methods
    async def history_orders_total(self, params: str) -> str: ...
    async def history_orders_get(self, params: str) -> str: ...
    async def history_deals_total(self, params: str) -> str: ...
    async def history_deals_get(self, params: str) -> str: ...

    # Market book methods
    async def market_book_add(self, params: str) -> str: ...
    async def market_book_get(self, params: str) -> str: ...
    async def market_book_release(self, params: str) -> str: ...

class Mt5Symbol:
    """MT5 symbol information."""

    name: str
    description: str
    path: str
    currency_base: str
    currency_profit: str
    currency_margin: str
    digits: int
    point: float
    trade_contract_size: float
    volume_min: float
    volume_max: float
    volume_step: float

class Mt5DataClientConfig:
    """Configuration for MT5 data client."""
    def __init__(
        self,
        mt5_base_url: str = "http://localhost:5000",
        update_instruments_interval_mins: Optional[int] = None,
    ) -> None: ...

class Mt5ExecutionClientConfig:
    """Configuration for MT5 execution client."""
    def __init__(
        self,
        mt5_base_url: str = "http://localhost:5000",
    ) -> None: ...

class Mt5InstrumentProviderConfig:
    """Configuration for MT5 instrument provider."""
    def __init__(
        self,
        load_all: bool = True,
        load_symbols: Optional[list[str]] = None,
    ) -> None: ...

class Mt5DataClient:
    """MT5 data client for NautilusTrader."""

    ...

class Mt5ExecutionClient:
    """MT5 execution client for NautilusTrader."""

    ...

class Mt5InstrumentProvider:
    """MT5 instrument provider for NautilusTrader."""

    ...
